# Generated by Django 4.0.5 on 2022-06-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(verbose_name='date published')),
                ('content', models.CharField(max_length=50)),
                ('completed', models.BooleanField()),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
